# Generated by Django 5.1.1 on 2024-09-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_plate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
