# Generated by Django 5.1.1 on 2024-09-13 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_plate_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='car',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Автомобить'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='number',
            field=models.CharField(max_length=6, verbose_name='Номер (А111АА)'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='owner',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Номер региона'),
        ),
    ]
